=== dixon01/Dev-Jasper/backend/Common/Protocols/Source/Ximple/Generic/dictionary.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="Dictionary">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="1" minOccurs="1" name="Version" />
        <xs:element  maxOccurs="1" minOccurs="1" name="Languages">
          <xs:complexType>
            <xs:sequence>
              <xs:element maxOccurs="unbounded" minOccurs="1" name="Language">
                <xs:complexType>
                  <xs:attribute name="Index" type="xs:unsignedByte" use="required" />
                  <xs:attribute name="Name" type="xs:string" use="required" />
                  <xs:attribute name="Description" type="xs:string" />
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element  maxOccurs="1" minOccurs="1" name="Tables">
          <xs:complexType>
            <xs:sequence>
              <xs:element maxOccurs="unbounded" minOccurs="1" name="Table">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="Description" type="xs:string" minOccurs="0" maxOccurs="1"/>
                    <xs:element maxOccurs="unbounded" name="Column" minOccurs="0">
                      <xs:complexType>
                        <xs:attribute name="Index" type="xs:unsignedByte" use="required" />
                        <xs:attribute name="Name" type="xs:string" use="required" />
                        <xs:attribute name="Description" type="xs:string" />
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                  <xs:attribute name="Index" type="xs:unsignedByte" use="required" />
                  <xs:attribute name="Name" type="xs:string" use="required" />
                  <xs:attribute name="MultiLanguage" type="xs:boolean" use="required" />
                  <xs:attribute name="MultiRow" type="xs:boolean" use="required" />
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== dixon01/Dev-Jasper/backend/Motion/SystemManager/Deploy/Config/BLT Example/PC-2/Config/Protran/dictionary.xml
<?xml version="1.0" encoding="utf-8"?>
<Dictionary
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="file:///. dictionary.xsd">
  <Version>2.0</Version>
  <Languages>
    <Language Index="0" Name="default" Description="Default language" />
    
    <!-- Western European languages -->
    <Language Index="1" Name="de" Description="German" />
    <Language Index="2" Name="en" Description="English" />
    <Language Index="3" Name="fr" Description="French" />
    <Language Index="4" Name="it" Description="Italian" />
    <Language Index="5" Name="es" Description="Spanish" />
    <Language Index="6" Name="pt" Description="Portugese" />

    <!-- Eastern European languages -->
    <Language Index="20" Name="ru" Description="Russian" />

    <!-- Middle Eastern languages -->
    <Language Index="40" Name="ar" Description="Arabic" />
    <Language Index="41" Name="he" Description="Hebrew" />

    <!-- Asian languages -->
    <Language Index="60" Name="zh" Description="Chinese" />
  </Languages>
  <Tables>
    <Table Index="0" Name="SystemStatus" MultiLanguage="false" MultiRow="false">
      <Description>Table containing all system information.</Description>
      <Column Index="0" Name="Date" Description="System date provided by Protran, but ad-hoc calculated in Infomedia as well" />
      <Column Index="1" Name="Time" Description="System time provided by Protran, but ad-hoc calculated in Infomedia as well" />
      <Column Index="2" Name="RemotePC" Description="Status of the remote PC (board computer)" />
      <Column Index="3" Name="StopRequestedState" Description="Set to 1 when stop was requested, otherwise 0" />
      <Column Index="4" Name="DoorStatus" Description="Status of the door: 0 = closed; 1 = open" />
      <Column Index="5" Name="SpecialInput" Description="Special input set to 1 when enabled, 0 when disabled" />
      <Column Index="6" Name="ExitSide" Description="Exit side: 0 = unknown; 1 = right; 2 = left; 3 = both" />
      <Column Index="7" Name="MovingDirection" Description="Moving direction: 0 = forward; 1 = reverse" />
    </Table>
    <Table Index="1" Name="PagingStatus" MultiLanguage="false" MultiRow="false">
      <Description>
        Table containing the page number and number of pages used in paging, these 
        values are generated by the Composer, not by Protran.
        Don't change these values since they are hardcoded in the Composer!
      </Description>
      <Column Index="0" Name="NumberOfPages" />
      <Column Index="1" Name="PageNumber" />
    </Table>
    <Table Index="10" Name="Route" MultiLanguage="true" MultiRow="false">
      <Description>Information about the current route</Description>
      <Column Index="0" Name="Line" Description="Line number" />
      <Column Index="1" Name="SpecialLine" Description="Special line symbol; from Infomedia 2.0 on, this is just the special line character" />
      <Column Index="2" Name="Region" Description="Region code" />
      <Column Index="3" Name="Punctuality" Description="Current punctuality information" />
      <Column Index="4" Name="CurrentStopIndex" Description="Current stop index" />
      <Column Index="5" Name="ApproachingStop" Description="Flag whether the bus is approaching the next stop (e.g. 100m before stop), set to 1 when approaching, otherwise 0" />
      <Column Index="6" Name="Trip" Description="Trip number (German: Fahrt)" />
      <Column Index="7" Name="Block" Description="Block number (German: Umlauf)" />
      <Column Index="8" Name="Run" Description="Run number (German: Kurs)" />
      <Column Index="9" Name="Route" Description="Route number" />
      <Column Index="10" Name="AnnouncementIndex" Description="Current announcement index" />
      <Column Index="11" Name="FareZone" Description="Ticketing fare zone" />
      <Column Index="12" Name="Deviation" Description="Information if the vehicle is deviating from its planned route" />
    </Table>
    <Table Index="11" Name="Destination" MultiLanguage="true" MultiRow="false">
      <Description>Name of the destination stop</Description>
      <Column Index="0" Name="DestinationName" Description="Name of the destination stop" />
      <Column Index="1" Name="DestinationCity" Description="Name of the destination city" />
      <Column Index="2" Name="DestinationInfo" Description="Additional information about the destination" />
      <Column Index="3" Name="DestinationTime" Description="Arrival time at the destination" />
      <Column Index="4" Name="DestinationDelay" Description="Delay information for the destination" />
      <Column Index="5" Name="DestinationTransferSymbols" Description="Transfer symbols for the destination stop" />
      <Column Index="6" Name="DestinationPlatform" Description="Platfrom at which the vehicle arrives" />
      <Column Index="7" Name="DestinationDeptartureTime" Description="Departure time from the destination" />
      <Column Index="8" Name="DestinationDistanceToNext" Description="Distance to the next stop in meters" />
    </Table>
    <Table Index="12" Name="Stops" MultiLanguage="true" MultiRow="true">
      <Description>Table containing all stop information.</Description>
      <Column Index="0" Name="StopName" Description="Name of the stop" />
      <Column Index="1" Name="StopCity" Description="Name of the stop city" />
      <Column Index="2" Name="StopInfo" Description="Additional information about the stop" />
      <Column Index="3" Name="StopTime" Description="Arrival time at the stop" />
      <Column Index="4" Name="StopDelay" Description="Delay at the stop" />
      <Column Index="5" Name="StopTransferSymbols" Description="Transfer symbols for the stop" />
      <Column Index="6" Name="StopPlatform" Description="Platfrom at which the vehicle arrives" />
      <Column Index="7" Name="StopDeptartureTime" Description="Departure time from the stop" />
      <Column Index="8" Name="StopDistanceToNext" Description="Distance to the next stop in meters" />
    </Table>
    <Table Index="13" Name="Connections" MultiLanguage="true" MultiRow="true">
      <Description>Table containing connection information for a single stop.</Description>
      <Column Index="0" Name="ConnectionTransportType" Description="Type of transport (bus, train, ...)" />
      <Column Index="1" Name="ConnectionLineNumber" Description="Line number of the connection" />
      <Column Index="2" Name="ConnectionLineSymbol" Description="Line name of the connection" />
      <Column Index="3" Name="ConnectionTime" Description="Departure time of the connection" />
      <Column Index="4" Name="ConnectionDestinationName" Description="Name of the destination stop of the connection" />
      <Column Index="5" Name="ConnectionDestinationCity" Description="Name of the destination city of the connection" />
      <Column Index="6" Name="ConnectionVia" Description="Name of the important intermediate (via) stops of the connection" />
      <Column Index="7" Name="ConnectionPlatform" Description="Name of the platform of the connection" />
      <Column Index="8" Name="ConnectionInfo" Description="Additional information about the connection" />
      <Column Index="9" Name="ConnectionDelay" Description="Delay information about the connection (e.g. +5 min)" />
    </Table>
    <Table Index="14" Name="ConnectionReference" MultiLanguage="true" MultiRow="false">
      <Description>Information about the stop for which Connections are to be shown.</Description>
      <Column Index="0" Name="ConnectionReferenceStopName" Description="Name of the stop" />
      <Column Index="1" Name="ConnectionReferenceStopCity" Description="Name of the stop city" />
      <Column Index="2" Name="ConnectionReferenceStopInfo" Description="Additional information about the stop" />
      <Column Index="3" Name="ConnectionReferenceStopTime" Description="Arrival time at the stop" />
      <Column Index="4" Name="ConnectionReferenceStopDelay" Description="Delay at the stop" />
      <Column Index="5" Name="ConnectionReferenceStopTransferSymbols" Description="Transfer symbols for the stop" />
      <Column Index="6" Name="ConnectionReferenceStopPlatform" Description="Platfrom at which the vehicle arrives" />
      <Column Index="7" Name="ConnectionReferenceStopDeptartureTime" Description="Departure time from the stop" />
      <Column Index="8" Name="ConnectionReferenceStopDistanceToNext" Description="Distance to the next stop in meters" />
    </Table>
    <Table Index="20" Name="PassengerMessages" MultiLanguage="true" MultiRow="true">
      <Description>Messages to the passengers</Description>
      <Column Index="0" Name="MessageType" Description="Type of the message (e.g. to show a special symbol depending on the type)" />
      <Column Index="1" Name="MessageTitle" Description="Title of the message (short text)" />
      <Column Index="2" Name="MessageText" Description="Text of the message (long text)" />
    </Table>
  </Tables>
</Dictionary>

=== dixon01/Dev-Jasper/backend/Motion/Infomedia/Tools/ComposerVisualizer/ComposerVisualizer/dictionary.xml
<?xml version="1.0" encoding="utf-8"?>
<Dictionary
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="file:///. dictionary.xsd">
  <Version>2.0</Version>
  <Languages>
    <Language Index="0" Name="en" />
  </Languages>
  <Tables>
    <Table Index="0" Name="SystemStatus">
      <Description>Table containing all system information.</Description>
      <Column Index="0" Name="Date" />
      <Column Index="1" Name="Time" />
      <Column Index="2" Name="RemotePC" />
      <Column Index="3" Name="StopRequestState"/>
      <Column Index="4" Name="DoorStatus"/>
    </Table>
    <Table Index="1" Name="PagingStatus">
      <Description>
        Table containing the page number and number of pages used in paging, these 
        values are generated by the Composer, not by Protran.
        Don't change these values since they are hardcoded in the Composer!
      </Description>
      <Column Index="0" Name="NumberOfPages" />
      <Column Index="1" Name="PageNumber" />
    </Table>
    <Table Index="10" Name="Route">
      <Description>Information about the current route</Description>
      <Column Index="0" Name="Line"/>
      <Column Index="1" Name="SpecialLine"/>
      <Column Index="2" Name="Region"/>
      <Column Index="3" Name="Punctuality"/>
    </Table>
    <Table Index="11" Name="Destination">
      <Description>Name of the destination stop</Description>
      <Column Index="0" Name="DestinationName"/>
      <Column Index="1" Name="DestinationCity"/>
      <Column Index="2" Name="DestinationInfo"/>
      <Column Index="3" Name="DestinationTime"/>
      <Column Index="4" Name="DestinationDelay"/>
      <Column Index="5" Name="DestinationTransferSymbols"/>
    </Table>
    <Table Index="12" Name="Stops">
      <Description>Table containing all stop information.</Description>
      <Column Index="0" Name="StopName" />
      <Column Index="1" Name="StopCity" />
      <Column Index="2" Name="StopInfo"/>
      <Column Index="3" Name="StopTime"/>
      <Column Index="4" Name="StopDelay"/>
      <Column Index="5" Name="StopTransferSymbols"/>
    </Table>
    <Table Index="13" Name="Connections">
      <Description></Description>
      <Column Index="0" Name="ConnectionTransportType"/>
      <Column Index="1" Name="ConnectionLineNumber"/>
      <Column Index="2" Name="ConnectionLineName"/>
      <Column Index="3" Name="ConnectionTime"/>
      <Column Index="4" Name="ConnectionDestinationName"/>
      <Column Index="5" Name="ConnectionDestinationCity"/>
      <Column Index="6" Name="ConnectionVia"/>
      <Column Index="7" Name="ConnectionPlatform"/>
      <Column Index="8" Name="ConnectionInfo"/>
      <Column Index="9" Name="ConnectionDelay"/>
    </Table>
    <Table Index="20" Name="PassengerMessages">
      <Description></Description>
      <Column Index="0" Name="MessageType"/>
      <Column Index="1" Name="MessageTitle"/>
      <Column Index="2" Name="MessageText"/>
    </Table>
  </Tables>
</Dictionary>
